throws.dkm: 39:例外Exceptionはthrows節に指定されるか、内部でcatchされなければなりません。
